[database]
driver = sql
username = postgres
database = hotties_factory_dev

# Default values for SQL driver
# host = localhost
# port = 5432
# password =

# test_database = hotties_factory_testing

# Memory drive for testing purposes
# driver = memory
