"""Create profiles table
Revision ID: 0444f81a90d5
Revises: af4c54b80ce2
Create Date: 2025-08-17 16:25:46.684934
"""

from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '0444f81a90d5'
down_revision: Union[str, Sequence[str], None] = 'af4c54b80ce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('name', sa.String(length=256), nullable=False),
        sa.Column('birthdate', sa.Date(), nullable=True),
        sa.Column('height', sa.Integer(), nullable=False),
        sa.Column('weight', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),

        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profiles')
    # ### end Alembic commands ###
