"""Add unique indexes
Revision ID: 41c4c93713bf
Revises: 156ca7cc29ec
Create Date: 2025-08-17 23:23:40.395228
"""

from alembic import op
from typing import Sequence, Union
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '41c4c93713bf'
down_revision: Union[str, Sequence[str], None] = '156ca7cc29ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profiles', ['user_id'])
    op.create_unique_constraint(None, 'sessions', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='unique')
    op.drop_constraint(None, 'profiles', type_='unique')
    # ### end Alembic commands ###
